# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  ImageName: 'eyasregistry2.azurecr.io/tempserver:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'eyasregistry2'
        repository: 'tempserver'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'