# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  ImageName: 'eyasregistry2.azurecr.io/tempserver:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'eyasregistry2'
        repository: 'tempserver'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - bash: |
        pip install pytest
        pip install pytest-cov
        pip install pytest-xdist
        pip install pytest-bdd
      displayName: 'Install test tools'
    - bash: 'pytest --junitxml=010.xml'
      displayName: "Run Unit Tests"
    - task: publishTestResults@2
      displayName: 'Publish test results'
      inputs:
        testRunTitle: 010
        testResultsFiles: '010.xml'
       