# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  ImageName: 'eyasregistry2.azurecr.io/tempserver:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'eyasregistry2'
        repository: 'tempserver'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: PythonScript@0
      inputs:
        scriptSource: inline
        script: |
          import glob
          stuff = glob.glob("*")
          for thing in stuff:
            print (thing)
    - bash: 'python -m pytest --junitxml=010.xml'
      workingDirectory: '.'
      displayName: 'Run tests'
    - task: publishTestResults@2
      displayName: 'Publish test results'
      inputs:
        testRunTitle: 010
        testResultsFiles: '010.xml'
       