# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  ImageName: 'eyasregistry2.azurecr.io/tempserver:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: Docker@2
      displayName: "login to ACR"
      inputs:
        command: login
        containerRegistry: 'eyasregistry2'
    - task: Docker@2
      inputs:
        containerRegistry: 'eyasregistry2'
        repository: 'temperature'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        arguments: '-t temperature-api:$(Build.BuildId)'
    - script: |
        docker run temperature-api:$(Build.BuildId) python -m pytest
      displayName: 'Run PyTest'